name = "codenames-matchmaking"
main = "worker.js"
compatibility_date = "2026-08-27"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[durable_objects.bindings]]
name = "DRAWING_ROOMS"
class_name = "DrawingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Matchmaker"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["DrawingRoom"]
